export const GET_TASKLISTS_START = 'GOOGLE_TASKS/GET_TASKLISTS_START';
export const GET_TASKLISTS_SUCCEED = 'GOOGLE_TASKS/GET_TASKLISTS_SUCCEED';
export const GET_TASKLISTS_FAIL = 'GOOGLE_TASKS/GET_TASKLISTS_FAIL';
