export const GET_TASKLIST_START = 'GOOGLE_TASKS/GET_TASKLIST_START';
export const GET_TASKLIST_SUCCEED = 'GOOGLE_TASKS/GET_TASKLIST_SUCCEED';
export const GET_TASKLIST_FAIL = 'GOOGLE_TASKS/GET_TASKLIST_FAIL';
