export const GET_TASKLIST_START = 'GOOGLE_TASKS/GET_TASKLIST_START';
export const GET_TASKLIST_SUCCEED = 'GOOGLE_TASKS/GET_TASKLIST_SUCCEED';
export const GET_TASKLIST_FAIL = 'GOOGLE_TASKS/GET_TASKLIST_FAIL';

export const INSERT_AND_GET_TASKLIST_START =
  'GOOGLE_TASKS/INSERT_AND_GET_TASKLIST_START';
export const INSERT_AND_GET_TASKLIST_SUCCEED =
  'GOOGLE_TASKS/INSERT_AND_GET_TASKLIST_SUCCEED';
export const INSERT_AND_GET_TASKLIST_FAIL =
  'GOOGLE_TASKS/INSERT_AND_GET_TASKLIST_FAIL';
